/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_1.h>
#include <MotorPWM_1_aliases.h>
#include <MotorPWM_1.h>
#include <Clock_1.h>
#include <Encoder_1_A_aliases.h>
#include <Encoder_1_A.h>
#include <Encoder_1_B_aliases.h>
#include <Encoder_1_B.h>
#include <Enable_1_aliases.h>
#include <Enable_1.h>
#include <Clock_2.h>
#include <Enable_2_aliases.h>
#include <Enable_2.h>
#include <MotorPWM_2_aliases.h>
#include <MotorPWM_2.h>
#include <Counter_3.h>
#include <PWM_3.h>
#include <ePin_aliases.h>
#include <ePin.h>
#include <Enable_5_aliases.h>
#include <Enable_5.h>
#include <Timer_2.h>
#include <isr_1.h>
#include <Clock_4.h>
#include <UART_1.h>
#include <Encoder_5_A_aliases.h>
#include <Encoder_5_A.h>
#include <isr_3.h>
#include <Timer_3.h>
#include <Clock_5.h>
#include <UART_2.h>
#include <MotorPWM_5_aliases.h>
#include <MotorPWM_5.h>
#include <Encoder_3_B_aliases.h>
#include <Encoder_3_B.h>
#include <Encoder_3_A_aliases.h>
#include <Encoder_3_A.h>
#include <PWM_2.h>
#include <Enable_3_aliases.h>
#include <Enable_3.h>
#include <MotorPWM_3_aliases.h>
#include <MotorPWM_3.h>
#include <Enable_4_aliases.h>
#include <Enable_4.h>
#include <MotorPWM_4_aliases.h>
#include <MotorPWM_4.h>
#include <foot12_aliases.h>
#include <foot12.h>
#include <foot34_aliases.h>
#include <foot34.h>
#include <Enable_6_aliases.h>
#include <Enable_6.h>
#include <MotorPWM_6_aliases.h>
#include <MotorPWM_6.h>
#include <foot78_aliases.h>
#include <foot78.h>
#include <PWM_5.h>
#include <MotorPWM_7_aliases.h>
#include <MotorPWM_7.h>
#include <PWM_4.h>
#include <foot56_aliases.h>
#include <foot56.h>
#include <Counter_1.h>
#include <Encoder_2_A_aliases.h>
#include <Encoder_2_A.h>
#include <Encoder_2_B_aliases.h>
#include <Encoder_2_B.h>
#include <Counter_2.h>
#include <Encoder_4_A_aliases.h>
#include <Encoder_4_A.h>
#include <Encoder_4_B_aliases.h>
#include <Encoder_4_B.h>
#include <Counter_4.h>
#include <Counter_5.h>
#include <Encoder_5_B_aliases.h>
#include <Encoder_5_B.h>
#include <Encoder_6_A_aliases.h>
#include <Encoder_6_A.h>
#include <Encoder_6_B_aliases.h>
#include <Encoder_6_B.h>
#include <Counter_6.h>
#include <Encoder_7_A_aliases.h>
#include <Encoder_7_A.h>
#include <Encoder_7_B_aliases.h>
#include <Encoder_7_B.h>
#include <Counter_7.h>
#include <Encoder_8_A_aliases.h>
#include <Encoder_8_A.h>
#include <Encoder_8_B_aliases.h>
#include <Encoder_8_B.h>
#include <Counter_8.h>
#include <MotorPWM_8_aliases.h>
#include <MotorPWM_8.h>
#include <Enable_7_aliases.h>
#include <Enable_7.h>
#include <Enable_8_aliases.h>
#include <Enable_8.h>
#include <startPin_aliases.h>
#include <startPin.h>
#include <LED1_aliases.h>
#include <LED1.h>
#include <LED2_aliases.h>
#include <LED2.h>
#include <LED3_aliases.h>
#include <LED3.h>
#include <LED4_aliases.h>
#include <LED4.h>
#include <LED5_aliases.h>
#include <LED5.h>
#include <pinA_aliases.h>
#include <pinA.h>
#include <UART_1_IntClock.h>
#include <UART_2_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

